### ISSUE TITLE
valid problem 

### ISSUE THREAD

**Issue by JiaxinQin0814** [Cranial-XIX/llm-pddl#4]
when running validate_plans.py 
I got FileNotFoundError: [Errno 2] No such file or directory: './downward/validate'
gould you please update a complete instruction on validating?

**Comment by JiaxinQin0814** [comment]
the official downward repo does not have a validate file inside it, how did you finish that?

**Comment by YuqianJiang** [comment]
`validate` is a 3rd party tool that is also used by Downward. You can compile it from https://github.com/KCL-Planning/VAL

Check [this page](https://github.com/aibasel/downward/blob/a80d46767301cbda270fa823af235024b24560e8/.github/workflows/ubuntu.yml#L179) for how it is installed inside Downward.

The commands are copied below:
```
git clone https://github.com/KCL-Planning/VAL.git
cd VAL
git checkout a5565396007eee73ac36527fbf904142b3077c74
make clean  # Remove old build artifacts and binaries.
sed -i 's/-Werror //g' Makefile  # Ignore warnings.
make -j2
mv validate ../
```

**Comment by Cranial-XIX** [comment]
I will mark this as closed. Please let us know if you have further questions.
