### ISSUE TITLE
Ground-truth Problem PDDL Generation

### ISSUE THREAD

**Issue by Emma1e** [Cranial-XIX/llm-pddl#7]
Hi, May I ask how did you generate the ground-truth Problem PDDL for each task in each domain?  Could you provide any scripts? 

Thank you!

**Comment by haomengz** [comment]
I think you could find the generation scripts in each domains folders. For example, for Barman: https://github.com/Cranial-XIX/llm-pddl/blob/main/domains/barman/description_generator.py

**Comment by haomengz** [comment]
@Emma1e I think you could find the generation scripts in each domains folders. For example, for Barman: https://github.com/Cranial-XIX/llm-pddl/blob/main/domains/barman/description_generator.py

**Comment by YuqianJiang** [comment]
Hi @Emma1e, the domains and the problems are from IPC. Some of the problems were manually adjusted. If you want additional problems in PDDL, I recommend checking out [the pddl-generators repo](https://github.com/AI-Planning/pddl-generators). The corresponding descriptions can be generated using the script @haomengz mentioned above.
